</sys/src/ape/config

CFLAGS=-c -FV+\
	-I..\
	-I../lib\
	-Icompat\
	-D_POSIX_SOURCE\
	-D_SUSV2_SOURCE\
	-D_PLAN9_SOURCE\
	-D__func__="<unknown>"\

OFILES=\
	chardata.$O\
	structdata.$O\
	memcheck.$O\
	minicheck.$O\
	runtests.$O\

LIB=/$objtype/lib/ape/libexpat.a

HFILES=\
	chardata.h\
	structdata.h\
	minicheck.h\
	memcheck.h\
	minicheck.h\

</sys/src/cmd/mkone
